# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-tests

# Trigger the workflow on any push.
on: push

jobs:
  tests:
    # NOTE: This name appears in GitHub's Checks API.
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install prerequisites
        run: |
          python -m pip install tox
      - name: Run tests
        run: |
          tox -e py38-tests
